### ISSUE TITLE
Conflict with UltiSnips

### ISSUE THREAD

**Issue by sassanh** [gisphm/vim-gitignore#1]
I'm using UltiSnips and I get this error when I open a `.gitignore` file:
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/sassanharadji/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/Users/sassanharadji/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 151, in snippets_in_current_scope
    snippets = self._snips(before, True)
File "/Users/sassanharadji/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 575, in _snips
    source.ensure(filetypes, cached=autotrigger_only)
  File "/Users/sassanharadji/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 47, in ensure
    self._load_snippets_for(ft)
  File "/Users/sassanharadji/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 80, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/Users/sassanharadji/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 99, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
SnippetSyntaxError: Invalid line '        *.i' in ~/.config/nvim/plugged/vim-gitignore/snippets/gitignore/CUDA.snippets:3
```

**Comment by sergei-dyshel** [comment]
Looks like Ultisnips is loading snippets from `snippets` directory which is intended only for Snipmate as there is separate `Ultisnips` directory. If you don't have other plugins which provides snippets in `snippets` directory that you need, you may add this to `.vimrc` and it will solve this problem:
```
let g:UltiSnipsSnipMateDirectories = ["Ultisnips"]
```

**Comment by sassanh** [comment]
Looking at docs I guess you mean `g:UltiSnipsSnippetDirectories` I set it and unfortunately it's not working for me. Did you try it yourself?

**Comment by sergei-dyshel** [comment]
You're right, it doesn't help. But this does:
```
let g:UltiSnipsEnableSnipMate = 0
```

**Comment by sassanh** [comment]
Thanks but unfortunately I have plugins that proved snippets and I need those snippets, it may help others though.

**Comment by wcn3** [comment]
I solved this by creating .vim/ftplugin/gitignore.vim

with the contents

let g:UltiSnipsEnableSnipMate=0

and that seems to work well.
